alert_index:
    path:     /
    defaults: { _controller: "AppBundle:Alert:index" }
    methods:  GET

alert_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Alert:show" }
    methods:  GET

alert_new:
    path:     /new
    defaults: { _controller: "AppBundle:Alert:new" }
    methods:  [GET, POST]

alert_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Alert:edit" }
    methods:  [GET, POST]

alert_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Alert:delete" }
    methods:  DELETE
