applicant_index:
    path:     /
    defaults: { _controller: "AppBundle:Applicant:index" }
    methods:  GET

applicant_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Applicant:show" }
    methods:  GET

applicant_new:
    path:     /new
    defaults: { _controller: "AppBundle:Applicant:new" }
    methods:  [GET, POST]

applicant_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Applicant:edit" }
    methods:  [GET, POST]

applicant_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Applicant:delete" }
    methods:  DELETE
