worklog_index:
    path:     /
    defaults: { _controller: "AppBundle:WorkLog:index" }
    methods:  GET

worklog_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:WorkLog:show" }
    methods:  GET

worklog_new:
    path:     /new
    defaults: { _controller: "AppBundle:WorkLog:new" }
    methods:  [GET, POST]

worklog_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:WorkLog:edit" }
    methods:  [GET, POST]

worklog_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:WorkLog:delete" }
    methods:  DELETE
