homepage:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }

app_jobvacancies:
    resource: "@AppBundle/Resources/config/routing/jobvacancy.yml"
    prefix:   /board/jobvacancy
app_applicant:
    resource: "@AppBundle/Resources/config/routing/applicant.yml"
    prefix:   /board/applicant
app_associattype:
    resource: "@AppBundle/Resources/config/routing/associatetype.yml"
    prefix:   /board/associatetype
app_associate:
    resource: "@AppBundle/Resources/config/routing/associate.yml"
    prefix:   /board/associate
app_worklog:
    resource: "@AppBundle/Resources/config/routing/worklog.yml"
    prefix:   /board/worklog
app_employee:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /board/employee
app_demandtype:
    resource: "@AppBundle/Resources/config/routing/demandtype.yml"
    prefix:   /board/demandtype
app_demand:
    resource: "@AppBundle/Resources/config/routing/demand.yml"
    prefix:   /board/demand
app_alert:
    resource: "@AppBundle/Resources/config/routing/alert.yml"
    prefix:   /board/alert
