AppBundle\Entity\Demand:
  type:  entity
  table: demand
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    message:
      type: text
  oneToOne:
    demandType:
      targetEntity: DemandType
      joinColumn:
        name: demand_type_id
        referencedColumnName: id
      nullable: false