AppBundle\Entity\Demand:
  type:  entity
  table: demand
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    message:
      type: text
    approved:
      type: boolean
      options:
        default: false
  manyToOne:
    demandType:
      targetEntity: DemandType
      joinColumn:
        name: demand_type_id
        referencedColumnName: id
      nullable: false
    user:
      targetEntity: AppBundle\Entity\User
      inversedBy: User
      joinColumn:
        name: user_id
        referencedColumnName: id