AppBundle\Entity\DemandType:
  type:  entity
  table: demand_type
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
  manyToOne:
    pdf:
      targetEntity: Pdf
      joinColumn:
        name: pdf_id
        referencedColumnName: id
      nullable: true
