AppBundle\Entity\User:
  type:  entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    first_name:
      type: string
      length: 200
    last_name:
      type: string
      length: 200
    address:
      type: string
      length: 200
      nullable: true
    phone:
      type: string
      length: 100
      nullable: true
    work_start_date:
      type: datetime
      nullable: false
    work_end_date:
      type: datetime
      nullable: true
  oneToMany:
    workLogs:
      targetEntity: WorkLog
      mappedBy: user
    demands:
      targetEntity: Demand
      mappedBy: user